version: '3'

services:
  triton:
    image: 'nvcr.io/nvidia/tritonserver:22.06-py3'
    env_file: .aws.env
    ports:
      - '8000:8000'
    command: ['tritonserver', '--model-repository=s3://nvidia-triton-server-dj-bucket/models/']

  face-bokeh:
    build: ./face-bokeh
    ports:
      - '8001:8001'

  face-emotion:
    build: ./face-emotion
    ports:
      - '8002:8002'
    
  myapp:
    build: .
    ports:
      - '8003:8003'
    depends_on:
      - face-bokeh
      - face-emotion

      